name: Continuous Integration

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build, Test & Publish
      working-directory: ./src/UserManagement.Web
      run: |
        dotnet restore
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal
        dotnet publish -o publish
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Artifact
        path: src/UserManagement.Web/publish
      

